# Generated by Django 5.0.7 on 2024-07-30 05:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='username',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'FEMALE')], max_length=2, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='username',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
